language: php

sudo: false

php:
    - 7.0
    - 7.1
    - hhvm
    - nightly

before_install:
    - sudo add-apt-repository ppa:nilarimogard/webupd8 -y
    - sudo apt-get update -q
    - sudo apt-get install youtube-dl

before_script:
    - composer install --no-interaction --prefer-source --dev

script:
    - phpunit
